x = 21
print(f'x = 21 : {x}')
x += 2
print(f'x += 2 : {x}')
x -= 2
print(f'x -= 2 : {x}')
x *= 2
print(f'x *= 2 : {x}')
x /= 2
print(f'x /= 2 : {x}')
x //= 2
print(f'x //= 2 : {x}')
x %= 2
print(f'x %= 2 : {x}')
x = 21
print(f'x = 21 : {x}')
x **= 2
print(f'x **= 2 : {x}')